branches:
  except:
    0_4_dev
language: python
python:
  - "2.6"
  - "2.7"
install: 
  - python setup.py develop
  - pip install coveralls
script:
  coverage run --source=inupypi setup.py test
after_success:
  coveralls
