#!/usr/bin/env python
# -*- coding: utf8 -*-

from argparse import ArgumentParser
from inupypi import app as application
from os import environ
from unipath import Path

config_file = 'config.ini'
parser = ArgumentParser(description='inupypi - PyPiServer based on Flask')
parser.add_argument('-c', '--config', help='inupypi config.ini')
args = parser.parse_args()
config_file = args.config or environ.get('INUPYPI_SETTINGS') or config_file

def main():
    global config_file
    config_file = Path(config_file).absolute()
    application.config.from_pyfile(config_file)
    application.run()

if __name__ == '__main__':
    main()
else:
    config_file = Path(config_file).absolute()
    application.config.from_pyfile(config_file)
