#!/usr/bin/env python
# -*- coding: utf8 -*-

from argparse import ArgumentParser
from inupypi import app as application
from os import environ
from unipath import Path

config_file = 'config.ini'
parser = ArgumentParser(description='inupypi - PyPiServer based on Flask')
parser.add_argument('-c', '--config', action='store',
        help='inupypi config.ini')
parser.add_argument('-k', '--host', action='store', default='127.0.0.1',
        help='inupypi host settings')
parser.add_argument('-p', '--port', action='store', default='5000',
        help='inupypi port settings')
args = parser.parse_args()
config_file = args.config or environ.get('INUPYPI_SETTINGS') or config_file
port = int(args.port)
host = args.host

def main():
    global config_file
    global host
    global port
    config_file = Path(config_file).absolute()
    application.config.from_pyfile(config_file)
    application.run(host=host,port=port)

if __name__ == '__main__':
    main()
else:
    config_file = Path(config_file).absolute()
    application.config.from_pyfile(config_file)
